substitutions:
  name: cat-wheel
  friendly_name: Cat Wheel
  yourtimezone: "Pacific/Auckland"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    then:
      - lambda: |-
          id(distance_today).update();
          id(distance_total).update();
          id(speed_max).update();
          id(speed_sensor).publish_state(0.0);
          id(last_rotation_time_persisted) = id(last_rotation_time);
          id(boot_time) = millis();

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: 
    ssid: "CatWheel Fallback"
    password: "grasshopper"

captive_portal:

web_server:
  port: 80
  
time:
  - platform: homeassistant
    id: my_time
    timezone: '${yourtimezone}'
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - script.execute: daily_reset

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT
      inverted: true
    name: "Wheel Sensor"
    id: hall_sensor
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - script.execute: record_rotation

  - platform: template
    name: "Activity"
    lambda: |-
      if (id(speed_sensor).state > 0.5) {
        return true;
      } else {
        return false;
      } 

sensor:
  - platform: template
    name: "Current Speed"
    id: speed_sensor
    lambda: |-
      return 0.0;
    unit_of_measurement: "km/hr"
    accuracy_decimals: 2
    icon: "mdi:speedometer"
    update_interval: never

  - platform: template
    name: "Distance Today"
    id: distance_today
    lambda: |-
      return id(distance_today_val) * 0.001;
    unit_of_measurement: "km"
    accuracy_decimals: 2
    icon: "mdi:run"
    update_interval: never

  - platform: template
    name: "Total Distance"
    id: distance_total
    lambda: |-
      return id(distance_total_val) * 0.001;
    unit_of_measurement: "km"
    accuracy_decimals: 2
    icon: "mdi:map-marker-distance"
    update_interval: never

  - platform: template
    name: "Max Speed"
    id: speed_max
    lambda: |-
      return id(speed_max_val) * 3.6;
    unit_of_measurement: "km/hr"
    accuracy_decimals: 2
    icon: "mdi:speedometer"
    update_interval: never
    
  - platform: template
    name: "Longest Session"
    id: longest_session_sensor
    lambda: |-
      return id(longest_session_duration) / 1000.0;
    unit_of_measurement: "s"
    accuracy_decimals: 0
    icon: "mdi:clock-outline"
    update_interval: never
    
  - platform: template
    name: "Current Session Duration"
    id: current_session_sensor
    lambda: |-
      return id(current_session_duration) / 1000.0;
    unit_of_measurement: "s"
    accuracy_decimals: 0
    icon: "mdi:timer-outline"
    update_interval: never
    
  - platform: template
    name: "Sessions Today"
    id: session_count_sensor
    lambda: |-
      return id(session_count_today);
    update_interval: never
    icon: "mdi:counter"
    
  - platform: uptime
    name: "ESP Uptime"


text_sensor:
  - platform: template
    name: "Last Movement"
    id: time_since_last_move
    update_interval: 10s
    lambda: |-
      uint32_t now = millis();
      uint32_t last = id(last_rotation_time_persisted);
      if (last == 0) {
        return {"Never"};
      }
      uint32_t diff = (now - last) / 1000;

      if (diff < 60) {
        char buffer[16];
        snprintf(buffer, sizeof(buffer), "%lus ago", diff);
        return {buffer};
      } else if (diff < 3600) {
        char buffer[16];
        snprintf(buffer, sizeof(buffer), "%lum ago", diff / 60);
        return {buffer};
      } else {
        char buffer[16];
        snprintf(buffer, sizeof(buffer), "%luh ago", diff / 3600);
        return {buffer};
      }

globals:
  - id: last_rotation_time_persisted
    type: uint32_t
    restore_value: yes
    initial_value: '0'

  - id: wheel_circumference
    type: float
    initial_value: '1.88'

  - id: last_rotation_time
    type: uint32_t
    restore_value: no
    initial_value: '0'

  - id: distance_today_val
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: distance_total_val
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: speed_max_val
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: boot_time
    type: unsigned long
    restore_value: no
    initial_value: '0'

  - id: session_start_time
    type: uint32_t
    restore_value: no
    initial_value: '0'

  - id: longest_session_duration
    type: uint32_t
    restore_value: yes
    initial_value: '0'
    
  - id: current_session_duration
    type: uint32_t
    restore_value: no
    initial_value: '0'
    
  - id: session_count_today
    type: uint32_t
    restore_value: yes
    initial_value: '0'

script:
  - id: record_rotation
    then:
      - lambda: |-
          static uint32_t last_rotation = 0;
          uint32_t now = millis();
          if (last_rotation != 0) {
            float delta_sec = (now - last_rotation) / 1000.0;
            if (delta_sec < 0.2) {
              ESP_LOGD("record_rotation", "Skipped rotation (too fast): %.2fs", delta_sec);
              return;
            }
            float speed = id(wheel_circumference) / delta_sec;
            id(speed_sensor).publish_state(speed * 3.6);
            if (speed > id(speed_max_val) + 0.1) {
              id(speed_max_val) = speed;
              id(speed_max).update();
            }
          }
          last_rotation = now;
          id(distance_today_val) += id(wheel_circumference);
          id(distance_total_val) += id(wheel_circumference);
          id(distance_today).update();
          id(distance_total).update();
          id(last_rotation_time) = now;
          id(last_rotation_time_persisted) = now;
          if (id(session_start_time) == 0) {
            id(session_start_time) = now;
          }
  - id: daily_reset
    then:
      - lambda: |-
          id(distance_today_val) = 0.0;
          id(speed_max_val) = 0.0;
          id(session_count_today) = 0;
          id(longest_session_duration) = 0;
          id(distance_today).update();
          id(speed_max).update();
          id(session_count_sensor).update();
          id(longest_session_sensor).update();

  - id: reset_all_stats
    then:
      - lambda: |-
          id(distance_today_val) = 0.0;
          id(distance_total_val) = 0.0;
          id(speed_max_val) = 0.0;
          id(distance_today).update();
          id(distance_total).update();
          id(speed_max).update();

  - id: noop_save_stats
    then:
      - logger.log: "Triggered noop_save_stats (values auto-persist)"

button:
  - platform: template
    name: "Reset All Stats"
    id: reset_all_button
    on_press:
      then:
        - script.execute: reset_all_stats

  - platform: restart
    name: "Reboot Device"
    id: reboot_button

  - platform: safe_mode
    name: "Reboot to Safe Mode"

  - platform: template
    name: "Factory Reset"
    id: factory_reset_button
    on_press:
      then:
        - script.execute: reset_all_stats
        - delay: 1s
        - button.press: reboot_button

interval:
  - interval: 1min
    then:
      - script.execute: noop_save_stats

  - interval: 500ms
    then:
      - lambda: |-
          uint32_t now = millis();
          if (id(last_rotation_time) != 0 && now - id(last_rotation_time) > 2000) {
            // Session has ended
            if (id(speed_sensor).state != 0.0) {
              id(speed_sensor).publish_state(0.0);
            }

            if (id(session_start_time) != 0) {
              uint32_t duration = now - id(session_start_time);
              if (duration > id(longest_session_duration)) {
                id(longest_session_duration) = duration;
                id(longest_session_sensor).update();
              }

              id(session_count_today) += 1;
              id(session_count_sensor).update();

              id(current_session_duration) = 0;
              id(current_session_sensor).update();  // <– This is fine, just runs once
              id(session_start_time) = 0;
            }

          } else if (id(session_start_time) != 0) {
            // Session is ongoing
            id(current_session_duration) = now - id(session_start_time);

            static uint32_t last_update_time = 0;
            if (now - last_update_time >= 1000) {  // Only update sensor every 1s
              id(current_session_sensor).update();
              last_update_time = now;
            }
          }
